### PR TITLE
Update projects to net7.0 TargetFramework with shared property

### PR DESCRIPTION
**Pull request by lbussell**
Fixes https://github.com/dotnet/command-line-api/issues/1792

From that issue:

> Source build requires projects to build with the current TFM or a supported netstandard TFM. command-line-api currently targets net6.0. Ideally this would be updated to net7.0. If that is not possible, the TFM could be conditioned for source-build but ideally the regular and source build would be identical.

### CODE REVIEW

**Comment by lbussell** [comment]
I'm seeing this error when testing locally:

> `/home/logan/vcs/command-line-api/src/System.CommandLine/Binding/ArgumentConverter.DefaultValues.cs(34,20): error IL2070: 'this' argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicParameterlessConstructor' in call to 'System.Type.GetConstructor(Type[])'. The parameter 'listType' of method 'System.CommandLine.Binding.ArgumentConverter.CreateEmptyList(Type)' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to. [/home/logan/vcs/command-line-api/src/System.CommandLine/System.CommandLine.csproj]`

Not sure what to change to fix this.

cc @jonsequitur

**Comment by MichaelSimons** [comment]
@jonsequitur - this is ready for a final review.

**Review by brettfo — APPROVED** [review]

**Comment by lbussell** [comment]
@jonsequitur, @brettfo, will these changes flow into SDK and eventually [installer/release/7.0.1xx](https://github.com/dotnet/installer/tree/release/7.0.1xx)? It's been a while since this was merged and usually changes flow by then. If not, then where do I need to backport this change to?

**Comment by MichaelSimons** [comment]
Ping @jonsequitur, @brettfo.

**Comment by nagilson** [comment]
Hi, we set up a darc feed for you https://github.com/dotnet/sdk/pull/28410

**Pull request merged**
