### PR TITLE
Add InvocationContext.GetHost extension method

### LINKED ISSUE #974: Provide access to IHost.Services inside 'UseMiddleware' method.
Perhaps there's already a way to accomplish this but I was unable to figure it out.  What I would like is:

``` csharp
commandLineBuilder.UseMiddleware(context =>
{
    //  'services' here would be the 'IHost.Services'
    var someService = services.GetService<ISomeService>();
}
```

I see that in the `UseHost` extension method, the `IHost` is placed in the `BindingContext.ServiceProvider` here:
``` csharp
invocation.BindingContext.AddService(typeof(IHost), _ => host);
```
However, the `BindingContext.ServiceProvider` is "internal" and so there's no way to get the `IHost`.  Otherwise something like this would be possible:
``` csharp
commandLineBuilder.UseMiddleware(context =>
{
    var host = context.BindingContext.ServiceProvider.GetService<IHost>();
    var someService = host.Services.GetService<ISomeService>();
}
```
Directly exposing the `BindingContext.ServiceProvider` is probably not the answer... perhaps providing another extension method including the `IHost.Services` would be best (if it's possible):
``` csharp
public static CommandLineBuilder UseMiddleware(
    this CommandLineBuilder builder, 
    Action<InvocationContext> onInvoke, 
    IServiceProvider services, // IHost.Services
    MiddlewareOrder order = MiddlewareOrder.Default);
```
Or perhaps just the `IHost` itself:

``` csharp
public static CommandLineBuilder UseMiddleware(
    this CommandLineBuilder builder, 
    Action<InvocationContext> onInvoke, 
    IHost host,
    MiddlewareOrder order = MiddlewareOrder.Default);
```

I'd be happy to try and contribute a PR if some guidance is provided on direction here.

### PR DESCRIPTION
**Pull request by fredrikhr**
Adds an extension method `GetHost` to `InvocationContext`, so that Command-line Middleware that runs after a call to `UseHost()` can access the created `IHost` instance easily.

It does technically not depend on using `UseHost()` since it simply news up a `ModelBinder<IHost>` and passes the Invocation `BindingContext` to it. Therefore, anyone adding `IHost` to the BindingContext service provider will be able to use this extension to access their `IHost`.

fixes #974

ref.: https://github.com/dotnet/command-line-api/issues/974#issuecomment-679167822

### CODE REVIEW

**Comment by jonsequitur** [comment]
Could you add a test that illustrates and verifies the use case?

**Comment by fredrikhr** [comment]
@jonsequitur Test added

**Comment by jonsequitur** [comment]
@fredrikhr Could you rebase this onto `main`?

**Review by jonsequitur — APPROVED** [review]

**Comment by fredrikhr** [comment]
@jonsequitur done, ready for merge

**Pull request merged**
