### PR TITLE
Added LegalFileNamesOnly to ArgumentExtensions

### PR DESCRIPTION
**Pull request by AronParker**
Fixes https://github.com/dotnet/command-line-api/issues/1224

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/command-line-api?pullRequest=1225) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/command-line-api?pullRequest=1225) before we can accept your contribution.<br/><br/>:x: AronParker [sign now](https://cla.dotnetfoundation.org/dotnet/command-line-api?pullRequest=1225)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/command-line-api?pullRequest=1225) it.</sub>

**Comment by jonsequitur** [comment]
Please add some tests.

**Comment by AronParker** [comment]
I added 4 test cases with a similar structure to LegalPathNamesOnly.

**Review by jonsequitur — APPROVED** [review]

**Comment by jonsequitur** [comment]
Thanks, @AronParker!

**Pull request merged**
