### PR TITLE
Sort suggestions by match index, then alphabetically

### PR DESCRIPTION
**Pull request by kimsey0**
Implements suggestion from https://github.com/dotnet/command-line-api/issues/12#issuecomment-625229936

### CODE REVIEW

**Comment by jonsequitur** [comment]
This is a nice solution to #12. Thanks, @kimsey0!

Could you add a unit test that demonstrates the behavior in `SuggestionTests`? (The tests there currently avoid asserting on the order of the suggestions (e.g. by using `BeEquivalentTo`), since this wasn't locked down. We have a `BeEquivalentSequenceTo` extension method which is a convenience for strict ordering.)

**Comment by kimsey0** [comment]
Sure! Would you like the existing tests to be changed to `BeEquivalentSequenceTo` too, or just some new tests?

**Comment by jonsequitur** [comment]
It's good to just add a test. The existing tests are intentionally unconcerned with suggestion order.

**Comment by kimsey0** [comment]
I've added two tests of suggestions for subcommands, one with text to match and one without. Is this sufficient? I was a bit unsure about the naming, since `SuggestionTests` seems to contain both `Noun_Sentence` and `Sentence` style test names.

**Comment by jonsequitur** [comment]
This looks great. Thanks, @kimsey0!

**Comment by kimsey0** [comment]
Thank you!

**Pull request merged**
