### PR TITLE
Add Arity to Option<T> ctor with multiple aliases

### PR DESCRIPTION
**Pull request by mahardan-oup**
Suggest adding IArgumentArity? arity argument to Option<T>(string[], string?) ctor.

This maintain parity with Option<T>(string, string?, IArgumentArity?) ctor and prevents much frustration when wanting to add a second alias to an Option requires rewriting the ctor altogether in order to keep the ArgumentArity.

### CODE REVIEW

**Comment by jonsequitur** [comment]
These constructors are already complex, and arity is a useful property to be able to set after construction.

I'd suggest instead that we add a property (`Option.Arity`?) that delegates to the internal `Argument.Arity` property.

**Comment by mahardan-oup** [comment]
If what you say is true, why have an Arity parameter in `Option(string, string?, IArgumentArity?)` ?
That's not to say there shouldn't be an `Option.Arity` property too, but adding the argument to the `Option(string[], string?)` ctor reduces perceived complexity from the developer's (my) point of view.

**Comment by jonsequitur** [comment]
I'm realizing that there are too many `Option` constructors overall. Some of these extra constructors are holdovers from when these classes were enforcing immutability, but arity is a less commonly used property and probably doesn't belong on any of the constructors.

I'll do a cleanup PR for this.

**Comment by mahardan-oup** [comment]
@jonsequitur Apologies - this is my first PR to a project like this. Do I close this PR when #1295 is closed \ merged or will it do it automatically?

**Comment by jonsequitur** [comment]
#1295  is merged and I believe it accomplishes the goal you were looking for by slightly different means. It exposes custom arity for `Option<T>` via a property instead of a constructor. It was a little more complex than I expected so as I investigated it, rather than asking you to do it, I just created a separate PR.

Feel free to close this and if you think there's still work to be done, please open an issue.

**Comment by mahardan-oup** [comment]
Closing.

**Pull request closed without merging**
