### PR TITLE
C# 9

### PR DESCRIPTION
**Pull request by jonsequitur**

### CODE REVIEW

**Comment by jonsequitur** [comment]
@omajid Any concerns with these changes? I've been poking at it to get it to build, but I'm probably missing some context on source build.

**Comment by omajid** [comment]
Hey @jonsequitur, this is targeted for consumption in the .NET 6.0 release, right?

The goal for these source-build patches is to minimize the dependency tree, and reduce the amount of packages needed to build System.CommandLine (and the entire .NET sdk).

The only impact I can expect from these changes would be adding/removing which dependencies are used. But that's okay for now. We have a plan to identify/catch/block changing the dependencies at a future date. See Stage 4 at  https://github.com/dotnet/source-build/blob/main/Documentation/planning/arcade-powered-source-build/implementation-plan.md#stage-descriptions

cc @dotnet/source-build-contrib

**Comment by jonsequitur** [comment]
Yes, System.CommandLine and dotnet-suggest (but not the other packages published from here) will have a stable release with .NET 6 or potentially sooner.

**Review by omajid — APPROVED** [review]
Thanks!

**Pull request merged**
