### PR TITLE
Keep newlines in descriptions

### LINKED ISSUE #960: Multiline description using help command
Hello there! 
-- ~~General Kenobi!~~ 

I have the following C# code:

```cs
var rootCommand = new RootCommand
                  {
                      new Option<bool>(new[] {"-d", "--debug"}, "Debug mode. Provides additional logging information while running."),
                      new Option<bool>(new[] {"-wi", "--what-if"}, "What-if mode. It provides additional logging information while running but not performs real actions.")
                  };

rootCommand.Description = "This application does blah-blah." +
                          "\nAnd bleh-bleh too." +
                          "\n\nAnd has a bunch of restrictions, like:" +
                          "\n\t- Bluh-Bluh;" +
                          "\n\t- Blih-Blih;" +
                          "\n\t- Bloh-Bloh.";

rootCommand.Handler = CommandHandler.Create<bool, bool>(SomeCoolRunProgramMethodThatIsNotNeededForThisIssue);
return rootCommand.Invoke(args);
```

And if I call `help` like this:
```
picolino@pc C:\MyCoolSourceFolder\ThatCoolApp\AwesomeApp.exe -?
```

I get that:
```
AwesomeApp:
  This application does blah-blah. And bleh-bleh too. And has a bunch of restrictions, like: - Bluh-Bluh; - Blih-Blih; - Bloh-Bloh.

Usage:
  AwesomeApp [options]

Options:
  -d, --debug       Debug mode. Provides additional logging information while running.
  -wi, --what-if    What-if mode. It provides additional logging information while running but not performs real actions.
  --version         Show version information
  -?, -h, --help    Show help and usage information
```

So the problem is I can't use a multiline description when using `help` command.
Is that a bug or classic "Microsoft feature"? Any workarounds for needed behavior?

Appreciate for any help 🤗

### PR DESCRIPTION
**Pull request by NextTurn**
Trying to resolve #960. Shall I change the global behaviors or add an option somewhere?

### CODE REVIEW

**Comment by picolino** [comment]
I think it must be a global behavior change.  
Because it is unpredictable that the system will remove `\n` or `\r\n` characters from description line.

**Comment by jonsequitur** [comment]
Thanks for working on this, @NextTurn. 

I agree with @picolino that it should just be a global behavior. It keeps things simple and it means we have fewer combinations to test.

Speaking of tests, a test that's worth adding is that both `\r\n` and `\n` should be replaced regardless of the current value of `Environment.NewLine`. Someone might create help using string literals or resource files resulting in `\n` being evaluated on Windows or `\r\n` being evaluated on Linux.

**Comment by NextTurn** [comment]
Almost there.

**Comment by jonsequitur** [comment]
@NextTurn, could you please add an option or argument to the [ApprovalTest case]( https://github.com/jonsequitur/command-line-api/blob/9cdcb230ac5f111aa8b602ed12e62cef458fa1cb/src/System.CommandLine.Tests/ApprovalTests/Help/HelpBuilderTests.Approval.cs#L14-L14) and update the [associated approval file](https://github.com/jonsequitur/command-line-api/blob/96da131652807fb37a571aba20a4eea73e718e1c/src/System.CommandLine.Tests/ApprovalTests/Help/Approvals/HelpBuilderTests.Help_describes_default_values_for_complex_root_command_scenario.approved.txt#L1-L1).

**Review by jonsequitur — APPROVED** [review]

**Comment by jonsequitur** [comment]
Thanks, @NextTurn!

**Comment by mristin** [comment]
Hi @jonsequitur ,
Do you know when is the next release planned  (even alpha or beta) which will include this feature?

**Pull request merged**
