### PR TITLE
fix generate name value for MethodInfo without Parameters

### PR DESCRIPTION
**Pull request by hessenar**

### CODE REVIEW

**Comment by jonsequitur** [comment]
Thanks! Could you add a test for this?

**Comment by hessenar** [comment]
> Thanks! Could you add a test for this?

done.

**Comment by hessenar** [comment]
> Thanks! Could you add a test for this?

Can you review this pr?

**Review by jonsequitur — APPROVED** [review]

**Comment by jonsequitur** [comment]
Thanks, @hessenar!

**Pull request merged**
